### ISSUE TITLE
Writing test for radar-pipeline

### ISSUE THREAD

**Issue by Hsankesara** [RADAR-base/radarpipeline#9]
Need to add some tests here which can check if every component in the pipeline is working.

**Comment by thepushkarp** [comment]
Hey, I was looking for ways to set up tests and I found this article: [How to create a Python package in 2022](https://mathspp.com/blog/how-to-create-a-python-package-in-2022), which covers a lot more than just setting up tests. Many of them can come in handy for this project.

We already have pre-commit hooks configured for formatting, so we can add tests integrated with that as well, so that it would always show failing tests before every commit.

**Comment by Hsankesara** [comment]
Hi @thepushkarp, I started writing some tests now. I just noticed that you also have a tests repo. Are you still working on the issue? If so, we could divide some tasks and finish it soon. (No worries if you can't work on it right now, though.)

**Comment by thepushkarp** [comment]
Hi @Hsankesara

Yes, I did start work on the tests initially, some initialization and basic stuff. You can go ahead if you're taking this up. Got some things on my plate at the moment so won't be able to pick most things up right now.

**Comment by Hsankesara** [comment]
Sounds good, I saw that you have added some tests. I'll merge them with my PR when I'm done
